### ISSUE TITLE
feat: Add Typesafe Config Directly to your jar file

### ISSUE THREAD

**Issue by m-karakus** [GoodforGod/liquibase-clickhouse#2]
I tried your jar from maven repo and it was giving dependency error, when I add typesafe-config jar to requested library folder it solved out. By default you can integrate it to your project. 

[Link](https://mvnrepository.com/artifact/com.typesafe/config)

**Comment by GoodforGod** [comment]
it is actually [provided by library](https://github.com/GoodforGod/liquibase-clickhouse/blob/master/build.gradle#L35)

Check your `build.gradle`, may be you excluded such dependency accidently
